@startuml

skinparam classAttributeIconSize 0

class Animal {
-name: String
#sound: String
+Sound(): String
}

class Mammal  {
+furColor: string
GiveBirth(): void {abstract}
}

class Bird {
+wingSpan: double
+Fly(): void
}

class Dog {
  +breed: string
  +Sit(): void
}

class Cat {
  +whiskerLength: double
  +ChaseMouse(): void
}

class Eagle {
  +beakLength: double
}

class Sparrow {
 +nestBuildingSkill: int
 
}

Animal <|-- Mammal
Animal <|-- Bird
Bird <|-- Eagle
Bird <|-- Sparrow
Mammal <|-- Dog
Mammal <|-- Cat

@enduml